#!/usr/bin/env bash
FILE="Man.txt"

check() {
	declare -n ref=$2
	if [[ ($1 =~ debug=.+) ]] || [[ ($1 =~ verbose=.+) ]] || [[ ($1 =~ file=.+) ]] || [[ -z $1 ]]
	then ref=$1
	else	
		echo ---------------------------------------
		echo Argument $3 -\> \"$1\" unrecognized.$'\n'The following arguments can be used:$'\n'-\> debug=yes$'\n'-\> verbose=yes$'\n'-\> file=FILENAME$'\n'Single argument \"man\" can also be used.
		echo ---------------------------------------
	fi
}

fst=""
snd=""
trd=""

[[ -n $1 ]] && [[ $1 != "man" ]] && check $1 fst "1"
[[ -n $2 ]] && check $2 snd "2"
[[ -n $3 ]] && check $3 trd "3"

if [[ $1 = "man" ]]
then 
	echo "╦ ╦╔═╗╦  ╔═╗╔═╗╔╦╗╔═╗  ╔╦╗╔═╗  ╔╗ ╔═╗╔╗ ╦ ╦";
	echo "║║║║╣ ║  ║  ║ ║║║║║╣    ║ ║ ║  ╠╩╗║ ║╠╩╗║║║";
	echo "╚╩╝╚═╝╩═╝╚═╝╚═╝╩ ╩╚═╝   ╩ ╚═╝  ╚═╝╚═╝╚═╝╚╩╝";
	cat "Man.txt"
else 
	echo "╔╗ ╔═╗╔╗ ╦ ╦";
	echo "╠╩╗║ ║╠╩╗║║║";
	echo "╚═╝╚═╝╚═╝╚╩╝";
fi

make compile $fst $snd $trd
